Gamify/Gamify/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('User.urls'), name='home'),
]

Gamify/User/urls.py
from django.urls import path
from .views import Registration, Login, PlayerView, Logout, Challenge

app_name='User'

urlpatterns = [
    path('', Login, name='login'),
    path('Register/', Registration, name='register'),
    path('Status/', PlayerView, name='status'),
    path('Logout/', Logout, name='logout'),
    path('Comp/', Challenge, name='complete'),
]

Gamify/User/models.py
from django.db import models
from django.contrib.auth.models import User
from status.models import  Challenge_Mind, Challenge_Body, Challenge_Skill

class Status(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    challenge_body = models.ForeignKey(Challenge_Body, default=1, on_delete=models.SET_DEFAULT)
    body_challenge_status = models.BooleanField(default=False)
    challenge_mind = models.ForeignKey(Challenge_Mind, default=1, on_delete=models.SET_DEFAULT)
    mind_challenge_status = models.BooleanField(default=False)
    challenge_skill = models.ForeignKey(Challenge_Skill, default=1, on_delete=models.SET_DEFAULT)
    skill_challenge_status = models.BooleanField(default=True)
    acc_date = models.DateField(default=1)

    character  = models.CharField(default=1, max_length=100)
    age = models.IntegerField(default=1)
    level = models.IntegerField(default=1)
    job = models.CharField(max_length=100,default="None")
    title = models.CharField(max_length=100,default="None")
    hp = models.IntegerField(default=100)
    strength = models.IntegerField(default=1)
    vitality = models.IntegerField(default=1)
    agility = models.IntegerField(default=1)
    intelligence = models.IntegerField(default=1)

    class Meta:
        verbose_name_plural = "Status"

    def __str__(self):
        return self.user.username

Gamify/status/models.py
from django.db import models


class Challenge_Body(models.Model):
    name = models.CharField(max_length=100)
    details = models.TextField()
    deadline = models.IntegerField()
    reward = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Challenge_Mind(models.Model):
    name = models.CharField(max_length=100)
    details = models.TextField()
    deadline = models.IntegerField()
    reward = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Challenge_Skill(models.Model):
    name = models.CharField(max_length=100)
    details = models.TextField()
    deadline = models.IntegerField()
    reward = models.CharField(max_length=100)

    def __str__(self):
        return self.name

Gamify/User/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class User_Registration(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2',
        ]
        widgets = {
            'username': forms.TextInput(attrs={"type":"text"}),
            'email': forms.TextInput(attrs={"type":"text"}),
            'password1': forms.TextInput(attrs={"type": "text"}),
            'password2': forms.TextInput(attrs={"type": "text"}),
        }

Gamify/User/views.py
from .lib import AssignPoints, CreateStatus
from .forms import User_Registration
from django.contrib import messages
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate


@login_required
def Challenge(request):
    AssignPoints(request)
    return redirect('/Status/')

@login_required
def PlayerView(request):
    stats = request.user.status
    user = request.user
    content = {'status': stats, 'user': user}
    return render(request, 'User/Status.html', content)

def Registration(request):
    if request.method == 'POST':
        form = User_Registration(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            login(request,user)
            CreateStatus(username)
            messages.success(request,f'{username} account created')
            return redirect('/Status/')
        else:
            for msg in form.error_messages:
                messages.error(request,f'{msg}:{form.error_messages[msg]}')
    form =User_Registration()
    content = {'form': form}
    return render(request,'User/Register.html',content)

@login_required
def Logout(request):
    logout(request)
    messages.info(request,'Logout successful')
    return redirect('/')

def Login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}")
                return redirect("Status/")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    content = {'form': form}
    return render(request, 'User/Login.html', content)

Gamify/status/views.py
from django.shortcuts import render
from User.models import Status
from django.contrib.auth.models import User

Gamify/User/templates/User/Login.html
{% extends 'User/base.html' %}

{% block title %}
Login
{% endblock title %}

{% block content %}
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<div class="container">
    <section class="card">
        <div class="card-content">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn blue">Login</button>
                <h5>Don't have an account? <a href="{% url 'User:register' %}">Register</a></h5>
            </form>
        </div>
    </section>
</div>
{% endblock content %}

Gamify/User/templates/User/Register.html
{% extends 'User/base.html' %}

{% block title %}
Register
{% endblock title %}

{% block content %}
<div class="container">
    <section class="card-panel">
        {% load static %}
        <form method="POST">
            {% csrf_token %}
            <i class="large material-icons center-align">account_circle</i>
            {{ form.as_p }}
            <button type="submit" class="btn blue white-text">Register</button>
            <h5 class="flow-text">Already have an account? <a href="{% url 'User:login' %}">Login</a></h5>
        </form>
    </section>
</div>
{% endblock content %}

Gamify/User/templates/User/Status.html
{% extends 'User/base.html' %}

{% block title %}
Status
{% endblock title %}

{% block sidenav %}
{% load static %}
<ul id="slide-out" class="sidenav sidenav-fixed">
    <li class="user-view">
        <div class="background" style="background: #00acc1;"></div>
        <i class="large material-icons">account_circle</i>
        <span class="name white-text">Name: {{user.username}}</span>
        <span class="title white-text">Title: {{user.status.title}}</span>
    </li>
    <div class="divider"></div>
    <li>
        <a href="{% url 'User:logout' %}">Logout</a>
    </li>
</ul>
{% endblock sidenav %}


{% block content %}
<div class="hide-on-med-and-down">
    <div class="row">
        <div class="col s12 m2 offset-m3">
            <div class="card-panel red accent-2">
                <h3 class="flow-text white-text center-align ">Strength</h3>
                <div class="divider"></div>
                <h5 class="flow-text white-text center-align ">{{status.strength}}</h5>
            </div>
        </div>
        <div class="col s12 m2 ">
            <div class="card-panel teal accent-4">
                <h3 class="flow-text white-text center-align">Vitality</h3>
                <div class="divider"></div>
                <h5 class="flow-text white-text center-align">{{status.vitality}}</h5>
            </div>
        </div>
        <div class="col s12 m2 ">
            <div class="card-panel light-blue darken-4">
                <h3 class="flow-text white-text center-align">Agility</h3>
                <div class="divider"></div>
                <h5 class="flow-text white-text center-align">{{status.agility}}</h5>
            </div>
        </div>
        <div class="col s12 m2 ">
            <div class="card-panel yellow darken-2">
                <h3 class="flow-text white-text center-align">Intelligence</h3>
                <div class="divider"></div>
                <h5 class="flow-text white-text center-align">{{status.intelligence}}</h5>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col s12 m8 offset-m3">
            <div class="card-panel center-align cyan darken-1">
                <h3 class=" white-text">Challenges</h3>
                <div class="row center">
                    <div class="col s4">
                        <div class="card-panel center-align yellow darken-2">
                            <h4 class="flow-text white-text">Mind</h4>
                            <div class="divider"></div>
                            <a class=" btn-flat white-text modal-trigger" href="#modal1">View challenge</a>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="card-panel center-align red accent-2">
                             <h4 class="flow-text white-text">Body</h4>
                            <div class="divider"></div>
                            <a class=" btn-flat white-text modal-trigger" href="#modal2">View challenge</a>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="card-panel center-align orange darken-4">
                            <h4 class="flow-text white-text">Skill</h4>
                            <div class="divider"></div>
                            <a class=" btn-flat white-text modal-trigger" href="#modal3">View challenge</a>
                        </div>
                    </div>
                </div>
                <a class="btn-large waves-effect waves-light teal" href="{% url 'User:complete' %}">Challenges Complete</a>
            </div>
        </div>
    </div>

    <div id="modal1" class="modal">
        <div class="modal-content">
            <h4>{{status.challenge_mind.name}}</h4>
            <br/>
            <p>{{status.challenge_mind.details}}</p>
        </div>
    </div>
    <div id="modal2" class="modal">
        <div class="modal-content">
            <h4>{{status.challenge_body.name}}</h4>
            <br/>
            <p>{{status.challenge_body.details}}</p>
        </div>
    </div>
    <div id="modal3" class="modal">
        <div class="modal-content">
            <h4>{{status.challenge_skill.name}}</h4>
            <br/>
            <p>{{status.challenge_skill.details}}</p>
        </div>
    </div>
</div>


<div class="hide-on-small-only hide-on-large-only">
    <div class="row">
        <div class="col s12 m3">
            <div class="card-panel red accent-2">
                <h3 class="flow-text white-text center-align ">Strength</h3>
                <div class="divider"></div>
                <h5 class="flow-text white-text center-align ">{{status.strength}}</h5>
            </div>
        </div>
        <div class="col s12 m3 ">
            <div class="card-panel teal accent-4">
                <h3 class="flow-text white-text center-align">Vitality</h3>
                <div class="divider"></div>
                <h5 class="flow-text white-text center-align">{{status.vitality}}</h5>
            </div>
        </div>
        <div class="col s12 m3 ">
            <div class="card-panel light-blue darken-4">
                <h3 class="flow-text white-text center-align">Agility</h3>
                <div class="divider"></div>
                <h5 class="flow-text white-text center-align">{{status.agility}}</h5>
            </div>
        </div>
        <div class="col s12 m3 ">
            <div class="card-panel yellow darken-2">
                <h3 class="flow-text white-text center-align">Intelligence</h3>
                <div class="divider"></div>
                <h5 class="flow-text white-text center-align">{{status.intelligence}}</h5>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col s12 m12">
            <div class="card-panel center-align cyan darken-1">
                <h3 class=" white-text">Challenges</h3>
                <div class="row center">
                    <div class="col s4">
                        <div class="card-panel center-align yellow darken-2">
                            <h4 class="flow-text white-text">Mind</h4>
                            <div class="divider"></div>
                            <a class=" btn-flat white-text modal-trigger" href="#modal1">View challenge</a>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="card-panel center-align red accent-2">
                             <h4 class="flow-text white-text">Body</h4>
                            <div class="divider"></div>
                            <a class=" btn-flat white-text modal-trigger" href="#modal2">View challenge</a>
                        </div>
                    </div>
                    <div class="col s4">
                        <div class="card-panel center-align orange darken-4">
                            <h4 class="flow-text white-text">Skill</h4>
                            <div class="divider"></div>
                            <a class=" btn-flat white-text modal-trigger" href="#modal3">View challenge</a>
                        </div>
                    </div>
                </div>
                <a class="btn-large waves-effect waves-light light-blue darken-4" href="{% url 'User:complete' %}">Challenges Complete</a>
            </div>
        </div>
    </div>

    <div id="modal1" class="modal">
        <div class="modal-content">
            <h4>{{status.challenge_mind.name}}</h4>
            <br/>
            <p>{{status.challenge_mind.details}}</p>
        </div>
    </div>
    <div id="modal2" class="modal">
        <div class="modal-content">
            <h4>{{status.challenge_body.name}}</h4>
            <br/>
            <p>{{status.challenge_body.details}}</p>
        </div>
    </div>
    <div id="modal3" class="modal">
        <div class="modal-content">
            <h4>{{status.challenge_skill.name}}</h4>
            <br/>
            <p>{{status.challenge_skill.details}}</p>
        </div>
    </div>
</div>

<div class="hide-on-med-and-up">
    <div class="row ">
        <div class="col s6">
            <div class="card-panel red accent-2">
                <h3 class="flow-text white-text center-align ">Strength</h3>
                <div class="divider"></div>
                <h5 class="flow-text white-text center-align ">{{status.strength}}</h5>
            </div>
        </div>
        <div class="col s6 ">
            <div class="card-panel teal accent-4">
                <h3 class="flow-text white-text center-align">Vitality</h3>
                <div class="divider"></div>
                <h5 class="flow-text white-text center-align">{{status.vitality}}</h5>
            </div>
        </div>
        <div class="col s6">
            <div class="card-panel light-blue darken-4">
                <h3 class="flow-text white-text center-align">Agility</h3>
                <div class="divider"></div>
                <h5 class="flow-text white-text center-align">{{status.agility}}</h5>
            </div>
        </div>
        <div class="col s6">
            <div class="card-panel yellow darken-2">
                <h3 class="flow-text white-text center-align">Intelligence</h3>
                <div class="divider"></div>
                <h5 class="flow-text white-text center-align">{{status.intelligence}}</h5>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col s12 m12">
            <div class="card-panel center-align cyan darken-1">
                <h3 class=" white-text">Challenges</h3>
                <div class="row center">
                    <div class="col s6">
                        <div class="card-panel center-align yellow darken-2">
                            <h4 class="flow-text white-text">Mind</h4>
                            <div class="divider"></div>
                            <a class=" btn-flat white-text modal-trigger" href="#modal1">View challenge</a>
                        </div>
                    </div>
                    <div class="col s6">
                        <div class="card-panel center-align red accent-2">
                             <h4 class="flow-text white-text">Body</h4>
                            <div class="divider"></div>
                            <a class=" btn-flat white-text modal-trigger" href="#modal1">View challenge</a>
                        </div>
                    </div>
                    <div class="col s6">
                        <div class="card-panel center-align orange darken-4">
                            <h4 class="flow-text white-text">Skill</h4>
                            <div class="divider"></div>
                            <a class=" btn-flat white-text modal-trigger" href="#modal1">View challenge</a>
                        </div>
                    </div>
                </div>
                <a class="btn-large waves-effect waves-light light-blue darken-4" href="{% url 'User:complete' %}">Challenges Complete</a>
            </div>
        </div>
    </div>

    <div id="modal4" class="modal">
        <div class="modal-content">
            <h4>{{status.challenge_mind.name}}</h4>
            <br/>
            <p>{{status.challenge_mind.details}}</p>
        </div>
    </div>
    <div id="modal2" class="modal">
        <div class="modal-content">
            <h4>{{status.challenge_body.name}}</h4>
            <br/>
            <p>{{status.challenge_body.details}}</p>
        </div>
    </div>
    <div id="modal3" class="modal">
        <div class="modal-content">
            <h4>{{status.challenge_skill.name}}</h4>
            <br/>
            <p>{{status.challenge_skill.details}}</p>
        </div>
    </div>
</div>
{% endblock content %}

Gamify/User/templates/User/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock title %}</title>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- font awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css"
        integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

    <!--Charts.js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha512-s+xg36jbIujB2S2VKfpGmlC3T5V2TF3lY48DX7u2r9XzGzgPsa6wTpOQA7J9iffvdeBN0q9tKzRxVxw1JviZPg==" crossorigin="anonymous"></script>

    <!-- Compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
</head>

<body>
    <header>
        <nav class="cyan darken-1">
            <div class="nav-wrapper">
                <div class="container">
                    <a href="#" class="sidenav-trigger" data-target="slide-out"><li class="material-icons">menu</li></a>
                    <span class="brand-logo center "><a href="/">Be more</a></span>
                </div>
            </div>
        </nav>
        {% block sidenav %}{% endblock sidenav %}
    </header>
    <br/>
    <br/>
{% if messages %}
    {% for message in messages %}
      <script>M.toast({html: "{{message}}", displayLength:2000});</script>
    {% endfor %}
{% endif %}
    <main>
        {% block content %} {% endblock content %}
    </main>

     <!-- Compiled and minified JavaScript -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>

    <script>
        $(document).ready(function(){
            $('.sidenav').sidenav();
            $('.modal').modal();
        });
    </script>

</body>
</html>